name: Generate snake animation

on:
  schedule:
    - cron: "0 */12 * * *"  
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Generate snake.svg (dark & light, themed)
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: maryamahmed0
          #           snake     eaten     background
          outputs: |
            dist/snake-dark.svg?palette=FF4DA6,FFA6D6,0D1117
            dist/snake-light.svg?palette=FF4DA6,FF7FBA,FFFFFF


      - name: Push snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
